version: "3.8"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes: 
      - /databases/pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  server: 
    image: tradelog-api
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - .:/app
    ports: 
      - 5000:5000
    